# Generated by Django 2.1.7 on 2019-08-02 08:15

import design.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import imagekit.models.fields
import model_utils.fields
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='design.Category', verbose_name='parent')),
            ],
            options={
                'verbose_name': '카테고리 품목',
                'verbose_name_plural': '카테고리 품목',
            },
        ),
        migrations.CreateModel(
            name='DeliveryOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='배송 방법')),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='배송 비용')),
                ('tax', models.BooleanField(default=False, verbose_name='부가세 포함여부')),
            ],
            options={
                'verbose_name': '상품옵션 _배송비',
                'verbose_name_plural': '상품옵션 _배송비',
            },
        ),
        migrations.CreateModel(
            name='EtcOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='기타 옵션')),
                ('option', models.CharField(blank=True, max_length=255, null=True, verbose_name='기타 옵션 상세')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='기타 옵션 메모')),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='기타 옵션 가격')),
            ],
            options={
                'verbose_name': '상품옵션 _기타옵션',
                'verbose_name_plural': '상품옵션 _기타옵션',
            },
        ),
        migrations.CreateModel(
            name='HooOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='후가공명')),
                ('option', models.CharField(blank=True, max_length=100, null=True, verbose_name='상위 품목')),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='후가공 가격')),
            ],
            options={
                'verbose_name': '상품옵션 _후가공',
                'verbose_name_plural': '상품옵션 _후가공',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('slug', models.SlugField(allow_unicode=True, help_text='A short label containing only letters, numbers, underscores or hyphens for URL', max_length=255, unique=True, verbose_name='slug')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='options', to='design.Category', verbose_name='category')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='design.Option', verbose_name='parent')),
            ],
            options={
                'verbose_name': '상품옵션 기타',
                'verbose_name_plural': '상품옵션 기타',
            },
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OrderImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('order_img_num', models.IntegerField(blank=True, null=True, verbose_name='이미지 넘버링')),
                ('plush_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='제목')),
                ('keyword', models.CharField(blank=True, max_length=255, verbose_name='키워드')),
                ('state_at', models.IntegerField(blank=True, choices=[(0, '대기'), (1, '수정완료'), (2, '확정'), (3, '보류'), (4, '취소'), (5, '무효처리')], default=0, null=True, verbose_name='시안 상태')),
                ('state', models.BooleanField(default=True, verbose_name='노출 상태')),
                ('images', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=design.models.OrderImg.upload_to_order, verbose_name='sample_img')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='링크 url')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.Category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '주문 3_시안',
                'verbose_name_plural': '주문 3_시안',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('today_num', models.IntegerField(default=1, verbose_name='today-넘버링')),
                ('joo_date', models.DateField(blank=True, null=True, verbose_name='주문일')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='발주일')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='업체명')),
                ('company_keyword', models.CharField(blank=True, max_length=255, null=True, verbose_name='업체 키워드')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='주소')),
                ('tell', models.CharField(blank=True, max_length=255, null=True, verbose_name='연락처')),
                ('state', models.IntegerField(blank=True, choices=[(0, '견적'), (1, '주문'), (2, '시안'), (3, '제작'), (4, '완료'), (5, '취소'), (6, '보류'), (7, '환불'), (8, '입금대기'), (9, '배송')], db_index=True, default=0, verbose_name='상태값')),
                ('tax', models.BooleanField(default=True, verbose_name='부가세포함')),
                ('keywords', models.CharField(blank=True, max_length=1000, null=True, verbose_name='검색창 내용')),
                ('checker', models.CharField(blank=True, max_length=255, null=True, verbose_name='시안 확인')),
                ('deposit', models.CharField(blank=True, max_length=100, null=True, verbose_name='입금 확인')),
                ('options', models.CharField(blank=True, max_length=255, null=True, verbose_name='결제/포함/택배')),
                ('employees', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='작업자')),
                ('fix_manager', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='담당자')),
                ('in_memo', models.CharField(blank=True, max_length=1000, null=True, verbose_name='관리자메모')),
                ('out_memo', models.CharField(blank=True, max_length=1000, null=True, verbose_name='고객표시 메모')),
                ('deposit_check', models.IntegerField(blank=True, null=True, verbose_name='입금 확인 및 차액')),
                ('uuid', models.UUIDField(default=uuid.uuid1)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='거래처')),
            ],
            options={
                'verbose_name': '주문 1_정보',
                'verbose_name_plural': '주문 1_정보',
            },
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('list_sort', models.IntegerField(db_index=True, verbose_name='내역 순서')),
                ('num', models.IntegerField(blank=True, null=True, verbose_name='동일 전표')),
                ('code', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='품목코드')),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='제품명')),
                ('standard', models.CharField(blank=True, max_length=1000, null=True, verbose_name='규격')),
                ('quantity', models.IntegerField(db_index=True, verbose_name='수량')),
                ('price', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11, null=True, verbose_name='매입가')),
                ('price_tax', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11, null=True, verbose_name='매입 부가세')),
                ('selling_price', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11, null=True, verbose_name='판매가')),
                ('selling_price_tax', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11, null=True, verbose_name='판매 부가세')),
                ('group_manage', models.CharField(blank=True, max_length=1000, null=True, verbose_name='관리 항목')),
                ('gram', models.CharField(blank=True, max_length=1000, null=True, verbose_name='기타')),
                ('etc', models.CharField(blank=True, max_length=1000, null=True, verbose_name='적요')),
                ('memo', models.CharField(blank=True, max_length=2000, null=True, verbose_name='메모')),
                ('order_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_list', to='design.OrderInfo', verbose_name='주문 정보')),
            ],
            options={
                'verbose_name': '주문 2_품목',
                'verbose_name_plural': '주문 2_품목',
            },
        ),
        migrations.CreateModel(
            name='OrderMemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('check', models.BooleanField(default=False, verbose_name='확인')),
                ('memo', models.CharField(blank=True, max_length=9000, null=True, verbose_name='내용')),
                ('location', models.CharField(blank=True, max_length=9000, null=True, verbose_name='위치 좌표')),
                ('order_img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.OrderImg', verbose_name='주문 이미지')),
            ],
            options={
                'verbose_name': '주문 4_시안 메모',
                'verbose_name_plural': '주문 4_시안 메모',
            },
        ),
        migrations.CreateModel(
            name='PaperOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='용지 이름')),
                ('gram', models.CharField(blank=True, max_length=100, null=True, verbose_name='그람수')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='색상')),
                ('option', models.CharField(blank=True, max_length=100, null=True, verbose_name='옵션 코팅/유무')),
            ],
            options={
                'verbose_name': '상품옵션 _용지옵션',
                'verbose_name_plural': '상품옵션 _용지옵션',
            },
        ),
        migrations.CreateModel(
            name='ProductBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='품목코드')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='품목명')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True, verbose_name='slug')),
                ('sell_price', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='판매가')),
                ('buy_price', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='매입가')),
                ('main_quantity', models.BooleanField(default=False, verbose_name='메인 수량')),
                ('ecount', models.BooleanField(default=False, verbose_name='이카운트 전송')),
                ('product_active', models.BooleanField(default=False, verbose_name='활성화')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_base_category', to='design.Category', verbose_name='카테고리')),
                ('etc', models.ManyToManyField(blank=True, related_name='product_base_etc', to='design.EtcOption')),
                ('paper', models.ManyToManyField(blank=True, related_name='product_base_paper', to='design.PaperOption')),
            ],
            options={
                'verbose_name': '상품옵션_통합',
                'verbose_name_plural': '상품옵션_통합',
            },
        ),
        migrations.CreateModel(
            name='ProductText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('standard', models.CharField(blank=True, max_length=255, null=True, verbose_name='규격명')),
                ('horizontal', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11, null=True, verbose_name='가로')),
                ('vertical', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11, null=True, verbose_name='세로')),
                ('width', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11, null=True, verbose_name='넓이')),
                ('height', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11, null=True, verbose_name='높이')),
                ('paper', models.CharField(blank=True, max_length=255, null=True, verbose_name='재질')),
                ('gram', models.CharField(blank=True, max_length=100, null=True, verbose_name='그람수')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='색상')),
                ('paper_option', models.CharField(blank=True, max_length=100, null=True, verbose_name='옵션 코팅/유무')),
                ('side', models.CharField(blank=True, max_length=100, null=True, verbose_name='양면 / 단면')),
                ('etc', models.CharField(blank=True, max_length=100, null=True, verbose_name='기타 정보')),
                ('etc_option', models.CharField(blank=True, max_length=100, null=True, verbose_name='기타 옵션 상세')),
                ('memo', models.CharField(blank=True, max_length=100, null=True, verbose_name='기타 옵션 메모')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='품목코드')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='품목명')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True, verbose_name='slug')),
                ('sell_price', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11, null=True, verbose_name='판매가')),
                ('buy_price', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11, null=True, verbose_name='매입가')),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11, null=True, verbose_name='메인 수량')),
                ('main_quantity', models.BooleanField(default=False, verbose_name='메인 수량')),
                ('ecount', models.BooleanField(default=True, verbose_name='이카운트 전송')),
                ('product_active', models.BooleanField(default=False, verbose_name='활성화')),
                ('product_version', models.IntegerField(blank=True, default=1, null=True, verbose_name='version')),
                ('group', models.IntegerField(blank=True, null=True, verbose_name='group')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.Category', verbose_name='카테고리')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='매입처')),
            ],
            options={
                'verbose_name': '상품옵션_통합 str',
                'verbose_name_plural': '상품옵션_통합 str',
            },
        ),
        migrations.CreateModel(
            name='SectorsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='design.SectorsCategory', verbose_name='parent')),
            ],
            options={
                'verbose_name': '카테고리 업종',
                'verbose_name_plural': '카테고리 업종',
            },
        ),
        migrations.CreateModel(
            name='SideOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='양면 / 단면')),
            ],
            options={
                'verbose_name': '상품옵션 _양면/단면',
                'verbose_name_plural': '상품옵션 _양면/단면',
            },
        ),
        migrations.CreateModel(
            name='StandardOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='품목명')),
                ('horizontal', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='가로')),
                ('vertical', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='세로')),
                ('width', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='넓이')),
                ('height', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='높이')),
            ],
            options={
                'verbose_name': '상품옵션 _기본 규격',
                'verbose_name_plural': '상품옵션 _기본 규격',
            },
        ),
        migrations.AddField(
            model_name='productbase',
            name='side',
            field=models.ManyToManyField(blank=True, related_name='product_base_side', to='design.SideOption'),
        ),
        migrations.AddField(
            model_name='productbase',
            name='standard',
            field=models.ManyToManyField(blank=True, related_name='product_base_standard', to='design.StandardOption'),
        ),
        migrations.AddField(
            model_name='productbase',
            name='supplier',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='매입처'),
        ),
        migrations.AddField(
            model_name='orderimg',
            name='order_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_img', to='design.OrderInfo', verbose_name='주문 리스트'),
        ),
        migrations.AddField(
            model_name='orderimg',
            name='sectors_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.SectorsCategory', verbose_name='업종'),
        ),
    ]
