# Generated by Django 2.1.7 on 2019-04-17 05:10

import design.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import model_utils.fields
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusuOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='A short label containing only letters, numbers, underscores or hyphens for URL', max_length=255, null=True, unique=True, verbose_name='slug')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='수량')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'verbose_name': '상품옵션 수량',
                'verbose_name_plural': '상품옵션 수량',
            },
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('slug', models.SlugField(allow_unicode=True, help_text='A short label containing only letters, numbers, underscores or hyphens for URL', max_length=255, unique=True, verbose_name='slug')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='design.Category', verbose_name='parent')),
            ],
            options={
                'verbose_name': '카테고리 품목',
                'verbose_name_plural': '카테고리 품목',
            },
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DosuOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('slug', models.SlugField(allow_unicode=True, help_text='A short label containing only letters, numbers, underscores or hyphens for URL', max_length=255, unique=True, verbose_name='slug')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DosuOption', to='design.Category', verbose_name='category')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='design.DosuOption', verbose_name='parent')),
            ],
            options={
                'verbose_name': '상품옵션 도수',
                'verbose_name_plural': '상품옵션 도수',
            },
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('slug', models.SlugField(allow_unicode=True, help_text='A short label containing only letters, numbers, underscores or hyphens for URL', max_length=255, unique=True, verbose_name='slug')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='options', to='design.Category', verbose_name='category')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='design.Option', verbose_name='parent')),
            ],
            options={
                'verbose_name': '상품옵션 기타',
                'verbose_name_plural': '상품옵션 기타',
            },
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OrderImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('order_img_num', models.IntegerField(blank=True, null=True, verbose_name='이미지 넘버링')),
                ('sample', models.CharField(blank=True, max_length=100, null=True, verbose_name='샘플명')),
                ('state', models.IntegerField(blank=True, choices=[(0, '대기'), (1, '수정완료'), (2, '확정'), (3, '보류'), (4, '취소'), (5, '무효처리')], default=0, null=True, verbose_name='시안 상태')),
                ('order_img', models.ImageField(blank=True, upload_to=design.models.OrderImg.upload_to_order, verbose_name='order_img')),
            ],
            options={
                'verbose_name': '주문 3_시안',
                'verbose_name_plural': '주문 3_시안',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('employees', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='작업자')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='업체명')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='주소')),
                ('tel', models.CharField(blank=True, max_length=100, null=True, verbose_name='연락처')),
                ('state', models.IntegerField(blank=True, choices=[(0, '견적'), (1, '주문'), (2, '완료'), (3, '입금대기'), (4, '취소'), (5, '보류'), (6, '환불')], db_index=True, default=0, verbose_name='상태값')),
                ('order_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='발주일')),
                ('keywords', models.CharField(blank=True, max_length=1000, null=True, verbose_name='검색창 내용')),
                ('checker', models.CharField(blank=True, max_length=100, null=True, verbose_name='시안 확인')),
                ('deposit', models.CharField(blank=True, max_length=100, null=True, verbose_name='입금 확인')),
                ('options', models.CharField(blank=True, max_length=100, null=True, verbose_name='결제/포함/택배')),
                ('uuid', models.UUIDField(default=uuid.uuid1)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='거래처')),
            ],
            options={
                'verbose_name': '주문 1_정보',
                'verbose_name_plural': '주문 1_정보',
            },
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('list_sort', models.IntegerField(db_index=True, verbose_name='내역 순서')),
                ('code', models.IntegerField(db_index=True, verbose_name='품목코드')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='제품명')),
                ('standard', models.CharField(blank=True, max_length=100, null=True, verbose_name='규격')),
                ('quantity', models.IntegerField(db_index=True, verbose_name='수량')),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=100, null=True, verbose_name='매입가')),
                ('price_tax', models.DecimalField(blank=True, decimal_places=4, max_digits=100, null=True, verbose_name='매입 부가세')),
                ('selling_price', models.DecimalField(blank=True, decimal_places=4, max_digits=100, null=True, verbose_name='판매가')),
                ('selling_price_tax', models.DecimalField(blank=True, decimal_places=4, max_digits=100, null=True, verbose_name='판매 부가세')),
                ('group_manage', models.CharField(blank=True, max_length=100, null=True, verbose_name='관리 항목')),
                ('info', models.CharField(blank=True, max_length=100, null=True, verbose_name='품목 정보')),
                ('memo', models.CharField(blank=True, max_length=100, null=True, verbose_name='메모')),
                ('order_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.OrderInfo', verbose_name='주문 정보')),
            ],
            options={
                'verbose_name': '주문 2_품목',
                'verbose_name_plural': '주문 2_품목',
            },
        ),
        migrations.CreateModel(
            name='OrderMemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('check', models.BooleanField(default=False, verbose_name='확인')),
                ('memo', models.CharField(blank=True, max_length=9000, null=True, verbose_name='내용')),
                ('location', models.CharField(blank=True, max_length=9000, null=True, verbose_name='위치 좌표')),
                ('order_img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.OrderImg', verbose_name='주문 이미지')),
            ],
            options={
                'verbose_name': '주문 4_시안 메모',
                'verbose_name_plural': '주문 4_시안 메모',
            },
        ),
        migrations.CreateModel(
            name='PaperOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('slug', models.SlugField(allow_unicode=True, help_text='A short label containing only letters, numbers, underscores or hyphens for URL', max_length=255, unique=True, verbose_name='slug')),
                ('gram', models.IntegerField(blank=True, null=True, verbose_name='그람수')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PaperOption', to='design.Category', verbose_name='category')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='design.PaperOption', verbose_name='parent')),
            ],
            options={
                'verbose_name': '상품옵션 용지',
                'verbose_name_plural': '상품옵션 용지',
            },
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=100, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=4, max_digits=100, null=True)),
                ('group_product', models.CharField(blank=True, max_length=100, null=True, verbose_name='품목 그룹')),
                ('group_manage', models.CharField(blank=True, max_length=100, null=True, verbose_name='관리 항목')),
                ('info', models.CharField(blank=True, max_length=100, null=True, verbose_name='품목 정보')),
                ('busu_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.BusuOption', verbose_name='수량 옵션')),
                ('dosu_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.DosuOption', verbose_name='도수 옵션')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.Option', verbose_name='기타 옵션')),
                ('paper_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.PaperOption', verbose_name='용지 옵션')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Profile', verbose_name='매입처')),
            ],
            options={
                'verbose_name': '상품옵션 최종 가격',
                'verbose_name_plural': '상품옵션 최종 가격',
            },
        ),
        migrations.CreateModel(
            name='SectorsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('slug', models.SlugField(allow_unicode=True, help_text='A short label containing only letters, numbers, underscores or hyphens for URL', max_length=255, unique=True, verbose_name='slug')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='design.SectorsCategory', verbose_name='parent')),
            ],
            options={
                'verbose_name': '카테고리 업종',
                'verbose_name_plural': '카테고리 업종',
            },
        ),
        migrations.CreateModel(
            name='StandardOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('slug', models.SlugField(allow_unicode=True, help_text='A short label containing only letters, numbers, underscores or hyphens for URL', max_length=255, unique=True, verbose_name='slug')),
                ('horizontal', models.DecimalField(blank=True, decimal_places=4, max_digits=100, null=True, verbose_name='가로')),
                ('vertical', models.DecimalField(blank=True, decimal_places=4, max_digits=100, null=True, verbose_name='세로')),
                ('width', models.DecimalField(blank=True, decimal_places=4, max_digits=100, null=True, verbose_name='넓이')),
                ('height', models.DecimalField(blank=True, decimal_places=4, max_digits=100, null=True, verbose_name='높이')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='StandardOption', to='design.Category', verbose_name='category')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='design.StandardOption', verbose_name='parent')),
            ],
            options={
                'verbose_name': '상품옵션 규격',
                'verbose_name_plural': '상품옵션 규격',
            },
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='productprice',
            name='standard_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.StandardOption', verbose_name='기본 옵션'),
        ),
        migrations.AddField(
            model_name='orderimg',
            name='order_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.OrderList', verbose_name='주문 품목'),
        ),
        migrations.AddField(
            model_name='busuoption',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BusuOption', to='design.Category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='busuoption',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='design.BusuOption', verbose_name='parent'),
        ),
    ]
