# Generated by Django 2.1.7 on 2019-03-29 08:43

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Profile', verbose_name='매입처'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='standard_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.StandardOption', verbose_name='기본 옵션'),
        ),
        migrations.AddField(
            model_name='paperoption',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PaperOption', to='design.Category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='paperoption',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='design.PaperOption', verbose_name='parent'),
        ),
        migrations.AddField(
            model_name='ordermemo',
            name='order_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.OrderImg', verbose_name='주문 이미지'),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='order_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.OrderInfo', verbose_name='주문 정보'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='employees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Employees', verbose_name='작업자'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Profile', verbose_name='거래처'),
        ),
        migrations.AddField(
            model_name='orderimg',
            name='order_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.OrderList', verbose_name='주문 품목'),
        ),
        migrations.AddField(
            model_name='option',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='options', to='design.Category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='option',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='design.Option', verbose_name='parent'),
        ),
        migrations.AddField(
            model_name='dosuoption',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DosuOption', to='design.Category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='dosuoption',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='design.DosuOption', verbose_name='parent'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='design.Category', verbose_name='parent'),
        ),
        migrations.AddField(
            model_name='busuoption',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BusuOption', to='design.Category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='busuoption',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='design.BusuOption', verbose_name='parent'),
        ),
    ]
