# Generated by Django 2.1.7 on 2019-04-22 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='배송 방법')),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='배송 비용')),
            ],
            options={
                'verbose_name': '상품옵션 _후가공',
                'verbose_name_plural': '상품옵션 _후가공',
            },
        ),
        migrations.CreateModel(
            name='EtcOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='기타 옵션')),
                ('option', models.CharField(blank=True, max_length=100, null=True, verbose_name='기타 옵션 상세')),
                ('memo', models.CharField(blank=True, max_length=100, null=True, verbose_name='기타 옵션 메모')),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='기타 옵션 가격')),
            ],
            options={
                'verbose_name': '상품옵션 _기타옵션',
                'verbose_name_plural': '상품옵션 _기타옵션',
            },
        ),
        migrations.CreateModel(
            name='HooOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='후가공명')),
                ('option', models.CharField(blank=True, max_length=100, null=True, verbose_name='후가공명')),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='후가공 가격')),
            ],
            options={
                'verbose_name': '상품옵션 _후가공',
                'verbose_name_plural': '상품옵션 _후가공',
            },
        ),
        migrations.CreateModel(
            name='ProductBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='품목코드')),
                ('title', models.CharField(max_length=128, verbose_name='품목명')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='A short label containing only letters, numbers, underscores or hyphens for URL', max_length=255, null=True, unique=True, verbose_name='slug')),
                ('horizontal', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='가로')),
                ('vertical', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='세로')),
                ('width', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='넓이')),
                ('height', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='높이')),
                ('sell_price', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='판매가')),
                ('buy_price', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='매입가')),
                ('main_quantity', models.BooleanField(default=False, verbose_name='메인 수량')),
                ('product_active', models.BooleanField(default=False, verbose_name='활성화')),
                ('ecount', models.BooleanField(default=False, verbose_name='이카운트 전송')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_base', to='design.Category', verbose_name='카테고리')),
                ('supplier', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='매입처')),
            ],
            options={
                'verbose_name': '상품옵션 규격',
                'verbose_name_plural': '상품옵션 규격',
            },
        ),
        migrations.CreateModel(
            name='SideOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='양면 / 단면')),
            ],
            options={
                'verbose_name': '상품옵션 _양면/단면',
                'verbose_name_plural': '상품옵션 _양면/단면',
            },
        ),
        migrations.RemoveField(
            model_name='busuoption',
            name='category',
        ),
        migrations.RemoveField(
            model_name='busuoption',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='dosuoption',
            name='category',
        ),
        migrations.RemoveField(
            model_name='dosuoption',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='busu_option',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='dosu_option',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='option',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='paper_option',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='standard_option',
        ),
        migrations.RemoveField(
            model_name='standardoption',
            name='category',
        ),
        migrations.RemoveField(
            model_name='standardoption',
            name='parent',
        ),
        migrations.AlterModelOptions(
            name='paperoption',
            options={'verbose_name': '상품옵션 _용지옵션', 'verbose_name_plural': '상품옵션 _용지옵션'},
        ),
        migrations.AlterModelManagers(
            name='paperoption',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='paperoption',
            name='category',
        ),
        migrations.RemoveField(
            model_name='paperoption',
            name='level',
        ),
        migrations.RemoveField(
            model_name='paperoption',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='paperoption',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='paperoption',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='paperoption',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='paperoption',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='paperoption',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='색상'),
        ),
        migrations.AddField(
            model_name='paperoption',
            name='option',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='옵션 코팅/유무'),
        ),
        migrations.AlterField(
            model_name='paperoption',
            name='gram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='그람수'),
        ),
        migrations.AlterField(
            model_name='paperoption',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='용지 이름'),
        ),
        migrations.DeleteModel(
            name='BusuOption',
        ),
        migrations.DeleteModel(
            name='DosuOption',
        ),
        migrations.DeleteModel(
            name='ProductPrice',
        ),
        migrations.DeleteModel(
            name='StandardOption',
        ),
    ]
