# Generated by Django 2.1.7 on 2019-04-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='매입가'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='price_tax',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='매입 부가세'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='판매가'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='selling_price_tax',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='판매 부가세'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='standardoption',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='높이'),
        ),
        migrations.AlterField(
            model_name='standardoption',
            name='horizontal',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='가로'),
        ),
        migrations.AlterField(
            model_name='standardoption',
            name='vertical',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='세로'),
        ),
        migrations.AlterField(
            model_name='standardoption',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='넓이'),
        ),
    ]
