# Generated by Django 2.1.7 on 2019-04-22 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_auto_20190422_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryoption',
            options={'verbose_name': '상품옵션 _배송비', 'verbose_name_plural': '상품옵션 _배송비'},
        ),
        migrations.AddField(
            model_name='deliveryoption',
            name='tax',
            field=models.BooleanField(default=False, verbose_name='부가세 포함여부'),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='supplier',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='매입처'),
        ),
    ]
