# Generated by Django 2.1.7 on 2019-04-01 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_auto_20190329_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderimg',
            old_name='sample_img',
            new_name='order_img',
        ),
    ]
