# Generated by Django 2.1.7 on 2019-04-22 15:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_auto_20190422_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='품목명')),
                ('horizontal', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='가로')),
                ('vertical', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='세로')),
                ('width', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='넓이')),
                ('height', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='높이')),
            ],
            options={
                'verbose_name': '상품옵션 _기본 규격',
                'verbose_name_plural': '상품옵션 _기본 규격',
            },
        ),
        migrations.AlterModelOptions(
            name='productbase',
            options={'verbose_name': '상품옵션_통합', 'verbose_name_plural': '상품옵션_통합'},
        ),
        migrations.RemoveField(
            model_name='productbase',
            name='height',
        ),
        migrations.RemoveField(
            model_name='productbase',
            name='horizontal',
        ),
        migrations.RemoveField(
            model_name='productbase',
            name='vertical',
        ),
        migrations.RemoveField(
            model_name='productbase',
            name='width',
        ),
        migrations.AddField(
            model_name='productbase',
            name='delivery',
            field=models.ManyToManyField(blank=True, related_name='product_base_delivery', to='design.DeliveryOption'),
        ),
        migrations.AddField(
            model_name='productbase',
            name='etc',
            field=models.ManyToManyField(blank=True, related_name='product_base_etc', to='design.EtcOption'),
        ),
        migrations.AddField(
            model_name='productbase',
            name='hoo',
            field=models.ManyToManyField(blank=True, related_name='product_base_hoo', to='design.HooOption'),
        ),
        migrations.AddField(
            model_name='productbase',
            name='paper',
            field=models.ManyToManyField(blank=True, related_name='product_base_paper', to='design.PaperOption'),
        ),
        migrations.AddField(
            model_name='productbase',
            name='side',
            field=models.ManyToManyField(blank=True, related_name='product_base_side', to='design.SideOption'),
        ),
        migrations.AlterField(
            model_name='hoooption',
            name='option',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='상위 품목'),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_base_category', to='design.Category', verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='품목명'),
        ),
        migrations.AddField(
            model_name='productbase',
            name='standard',
            field=models.ManyToManyField(blank=True, related_name='product_base_standard', to='design.StandardOption'),
        ),
    ]
