# Generated by Django 2.1.7 on 2019-08-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_auto_20190806_1801'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='sectorscategory',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='sectorscategory',
            name='slug',
        ),
    ]
