# Generated by Django 2.1.7 on 2019-05-19 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_auto_20190423_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbase',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='productbase',
            name='hoo',
        ),
    ]
