# Generated by Django 2.1.7 on 2019-05-19 03:59

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0005_auto_20190519_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='카테고리')),
                ('supplier', models.CharField(blank=True, max_length=255, null=True, verbose_name='매입처')),
                ('standard', models.CharField(blank=True, max_length=255, null=True, verbose_name='규격명')),
                ('horizontal', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='가로')),
                ('vertical', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='세로')),
                ('width', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='넓이')),
                ('height', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='높이')),
                ('paper', models.CharField(blank=True, max_length=255, null=True)),
                ('gram', models.CharField(blank=True, max_length=100, null=True, verbose_name='그람수')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='색상')),
                ('paper_option', models.CharField(blank=True, max_length=100, null=True, verbose_name='옵션 코팅/유무')),
                ('side', models.CharField(blank=True, max_length=100, null=True, verbose_name='양면 / 단면')),
                ('etc', models.CharField(blank=True, max_length=100, null=True, verbose_name='옵션 코팅/유무')),
                ('etc_option', models.CharField(blank=True, max_length=100, null=True, verbose_name='기타 옵션 상세')),
                ('memo', models.CharField(blank=True, max_length=100, null=True, verbose_name='기타 옵션 메모')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='품목코드')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='품목명')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True, verbose_name='slug')),
                ('sell_price', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='판매가')),
                ('buy_price', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='매입가')),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='메인 수량')),
                ('main_quantity', models.BooleanField(default=False, verbose_name='메인 수량')),
                ('ecount', models.BooleanField(default=False, verbose_name='이카운트 전송')),
                ('product_active', models.BooleanField(default=False, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '상품옵션_통합 str',
                'verbose_name_plural': '상품옵션_통합 str',
            },
        ),
    ]
