# Generated by Django 2.1.7 on 2019-08-07 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0005_auto_20190806_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='sectorscategory',
            name='slug',
        ),
    ]
