# Generated by Django 2.1.7 on 2019-05-19 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('design', '0006_producttext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttext',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.Category', verbose_name='카테고리'),
        ),
        migrations.RemoveField(
            model_name='producttext',
            name='supplier',
        ),
        migrations.AddField(
            model_name='producttext',
            name='supplier',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='매입처'),
        ),
    ]
