# Generated by Django 2.1.7 on 2019-08-08 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0006_auto_20190807_1333'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='sectorscategory',
            name='is_removed',
        ),
    ]
