# Generated by Django 2.1.7 on 2019-05-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0007_auto_20190519_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttext',
            name='supplier',
        ),
        migrations.AddField(
            model_name='producttext',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='매입처'),
        ),
    ]
