# Generated by Django 2.1.7 on 2019-08-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0007_auto_20190808_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderimg',
            name='employees',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='업로더'),
        ),
    ]
