# Generated by Django 2.1.7 on 2019-05-20 04:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('design', '0008_auto_20190520_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttext',
            name='supplier',
        ),
        migrations.AddField(
            model_name='producttext',
            name='supplier',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='매입처'),
        ),
    ]
