# Generated by Django 2.1.7 on 2019-05-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0009_auto_20190520_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttext',
            name='etc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='기타 정보'),
        ),
    ]
