# Generated by Django 2.1.7 on 2019-09-27 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0010_cartproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryOption',
        ),
        migrations.DeleteModel(
            name='HooOption',
        ),
        migrations.RemoveField(
            model_name='productbase',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productbase',
            name='etc',
        ),
        migrations.RemoveField(
            model_name='productbase',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='productbase',
            name='side',
        ),
        migrations.RemoveField(
            model_name='productbase',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='productbase',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='EtcOption',
        ),
        migrations.DeleteModel(
            name='PaperOption',
        ),
        migrations.DeleteModel(
            name='ProductBase',
        ),
        migrations.DeleteModel(
            name='SideOption',
        ),
        migrations.DeleteModel(
            name='StandardOption',
        ),
    ]
