# Generated by Django 2.1.7 on 2019-06-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0010_auto_20190531_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttext',
            name='product_version',
            field=models.IntegerField(blank=True, null=True, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='producttext',
            name='ecount',
            field=models.BooleanField(default=True, verbose_name='이카운트 전송'),
        ),
        migrations.AlterField(
            model_name='producttext',
            name='paper',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='재질'),
        ),
    ]
