# Generated by Django 2.1.7 on 2019-09-27 08:29

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0011_auto_20190927_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('size', models.CharField(blank=True, max_length=255, null=True, verbose_name='규격 size')),
                ('paper', models.CharField(blank=True, max_length=255, null=True, verbose_name='용지 paper')),
                ('side', models.CharField(blank=True, max_length=255, null=True, verbose_name='인쇄 side')),
                ('deal', models.CharField(blank=True, max_length=255, null=True, verbose_name='수량 deal')),
                ('option1', models.CharField(blank=True, max_length=255, null=True, verbose_name='옵션1 option1')),
                ('option2', models.CharField(blank=True, max_length=255, null=True, verbose_name='옵션1 option2')),
                ('supplier', models.CharField(blank=True, max_length=255, null=True, verbose_name='매입')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='메모 memo')),
                ('sell', models.DecimalField(blank=True, decimal_places=4, max_digits=11, verbose_name='sell')),
                ('buy', models.DecimalField(blank=True, decimal_places=4, max_digits=11, verbose_name='buy')),
            ],
            options={
                'verbose_name': '가격 리턴 api',
                'verbose_name_plural': '가격 리턴 api',
            },
        ),
    ]
