# Generated by Django 2.1.7 on 2019-06-05 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('design', '0011_auto_20190605_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttext',
            name='supplier',
        ),
        migrations.AddField(
            model_name='producttext',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='매입처'),
        ),
    ]
