# Generated by Django 2.1.7 on 2019-06-05 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0012_auto_20190605_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttext',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.Category', verbose_name='카테고리'),
        ),
    ]
