# Generated by Django 2.1.7 on 2019-09-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0012_productpriceapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpriceapi',
            name='buy',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11, verbose_name='buy'),
        ),
        migrations.AlterField(
            model_name='productpriceapi',
            name='sell',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11, verbose_name='sell'),
        ),
    ]
