# Generated by Django 2.1.7 on 2019-06-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0013_auto_20190605_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttext',
            name='group',
            field=models.IntegerField(blank=True, null=True, verbose_name='group'),
        ),
    ]
