# Generated by Django 2.1.7 on 2019-06-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0014_producttext_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='tel',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='company_keyword',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='업체 키워드'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='in_memo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='관리자메모'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='joo_date',
            field=models.DateField(blank=True, null=True, verbose_name='주문일'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='manager',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='담당자'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='num',
            field=models.IntegerField(blank=True, null=True, verbose_name='동일 전표'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='out_memo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='고객표시 메모'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='tax',
            field=models.BooleanField(default=True, verbose_name='부가세포함'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='tell',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='연락처'),
        ),
        migrations.AlterField(
            model_name='etcoption',
            name='memo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='기타 옵션 메모'),
        ),
        migrations.AlterField(
            model_name='etcoption',
            name='option',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='기타 옵션 상세'),
        ),
        migrations.AlterField(
            model_name='etcoption',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='기타 옵션'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='checker',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='시안 확인'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='업체명'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='options',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='결제/포함/택배'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='발주일'),
        ),
    ]
