# Generated by Django 2.1.7 on 2019-06-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0015_auto_20190610_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='code',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='품목코드'),
        ),
    ]
