# Generated by Django 2.1.7 on 2019-06-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0016_auto_20190611_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='num',
        ),
        migrations.AddField(
            model_name='orderlist',
            name='num',
            field=models.IntegerField(blank=True, null=True, verbose_name='동일 전표'),
        ),
    ]
