# Generated by Django 2.1.7 on 2019-09-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0017_auto_20190930_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorderproduct',
            name='deal_value',
        ),
        migrations.RemoveField(
            model_name='customerorderproduct',
            name='option1_value',
        ),
        migrations.RemoveField(
            model_name='customerorderproduct',
            name='option2_value',
        ),
        migrations.RemoveField(
            model_name='customerorderproduct',
            name='paper_value',
        ),
        migrations.RemoveField(
            model_name='customerorderproduct',
            name='side_value',
        ),
        migrations.RemoveField(
            model_name='customerorderproduct',
            name='size_value',
        ),
        migrations.AddField(
            model_name='customerorderproduct',
            name='deal_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='수량 deal text'),
        ),
        migrations.AddField(
            model_name='customerorderproduct',
            name='option1_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='옵션1 option1 text'),
        ),
        migrations.AddField(
            model_name='customerorderproduct',
            name='option2_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='옵션1 option2 text'),
        ),
        migrations.AddField(
            model_name='customerorderproduct',
            name='paper_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='용지 paper text'),
        ),
        migrations.AddField(
            model_name='customerorderproduct',
            name='side_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='인쇄 side text'),
        ),
        migrations.AddField(
            model_name='customerorderproduct',
            name='size_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='규격 size text'),
        ),
        migrations.AddField(
            model_name='productpriceapi',
            name='deal_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='수량 deal text'),
        ),
        migrations.AddField(
            model_name='productpriceapi',
            name='option1_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='옵션1 option1 text'),
        ),
        migrations.AddField(
            model_name='productpriceapi',
            name='option2_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='옵션1 option2 text'),
        ),
        migrations.AddField(
            model_name='productpriceapi',
            name='paper_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='용지 paper text'),
        ),
        migrations.AddField(
            model_name='productpriceapi',
            name='side_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='인쇄 side text'),
        ),
        migrations.AddField(
            model_name='productpriceapi',
            name='size_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='규격 size text'),
        ),
    ]
