# Generated by Django 2.1.7 on 2019-06-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0018_auto_20190611_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, '견적'), (1, '주문'), (2, '시안'), (3, '완료'), (4, '전체'), (5, '취소'), (6, '보류'), (7, '환불'), (8, '입금대기')], db_index=True, default=0, verbose_name='상태값'),
        ),
    ]
