# Generated by Django 2.1.7 on 2019-09-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0018_auto_20190930_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpriceapi',
            name='kind',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='품목 종류'),
        ),
    ]
