# Generated by Django 2.1.7 on 2019-09-30 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('design', '0019_productpriceapi_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartPriceProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('json_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='json data')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='고객')),
            ],
            options={
                'verbose_name': '카트 가격 변동 json 텍스트',
                'verbose_name_plural': '카트 가격 변동 json 텍스트',
            },
        ),
    ]
