# Generated by Django 2.1.7 on 2019-09-30 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0020_cartpriceproblem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerorderproduct',
            old_name='sectors_category',
            new_name='customer_order_info',
        ),
    ]
