# Generated by Django 2.1.7 on 2019-06-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0020_auto_20190625_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='today_num',
            field=models.IntegerField(default=1, verbose_name='today-넘버링'),
        ),
    ]
