# Generated by Django 2.1.7 on 2019-06-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0021_orderinfo_today_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='info',
        ),
        migrations.AddField(
            model_name='orderlist',
            name='etc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='적요'),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='gram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='기타'),
        ),
    ]
