# Generated by Django 2.1.7 on 2019-10-08 05:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0023_auto_20191001_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceInsideAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('supplier', models.CharField(blank=True, max_length=255, null=True, verbose_name='매입')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='메모 memo')),
                ('buy', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11, verbose_name='buy')),
            ],
            options={
                'verbose_name': '가격 내부 api',
                'verbose_name_plural': '가격 내부 api',
            },
        ),
        migrations.RemoveField(
            model_name='productpriceapi',
            name='buy',
        ),
        migrations.RemoveField(
            model_name='productpriceapi',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='productpriceapi',
            name='supplier',
        ),
        migrations.AddField(
            model_name='productpriceinsideapi',
            name='price_api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.ProductPriceAPI', verbose_name='product api pk'),
        ),
    ]
