# Generated by Django 2.1.7 on 2019-06-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0023_auto_20190627_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='in_memo',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='관리자메모'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='out_memo',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='고객표시 메모'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='etc',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='적요'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='gram',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='기타'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='group_manage',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='관리 항목'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='memo',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='메모'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='제품명'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='standard',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='규격'),
        ),
    ]
