# Generated by Django 2.1.7 on 2019-10-10 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0024_auto_20191008_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorderproduct',
            name='sell_opposition',
        ),
        migrations.RemoveField(
            model_name='customerorderproduct',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='productpriceinsideapi',
            name='price_api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_api_inside', to='design.ProductPriceAPI', verbose_name='product api pk'),
        ),
    ]
