# Generated by Django 2.1.7 on 2019-07-03 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0024_auto_20190628_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='is_removed',
        ),
    ]
