# Generated by Django 2.1.7 on 2019-10-10 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0025_auto_20191010_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorderproduct',
            name='customer_order_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_order_product', to='design.CustomerOrderInfo', verbose_name='고객 주문 정보'),
        ),
    ]
