# Generated by Django 2.1.7 on 2019-07-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0025_remove_orderlist_is_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='deposit_check',
            field=models.IntegerField(blank=True, null=True, verbose_name='입금 확인 및 차액'),
        ),
    ]
