# Generated by Django 2.1.7 on 2019-07-16 06:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0026_orderinfo_deposit_check'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderimg',
            old_name='order_img',
            new_name='images',
        ),
        migrations.RemoveField(
            model_name='orderimg',
            name='order_list',
        ),
        migrations.RemoveField(
            model_name='orderimg',
            name='sample',
        ),
        migrations.AddField(
            model_name='orderimg',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.Category', verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='orderimg',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, verbose_name='키워드'),
        ),
        migrations.AddField(
            model_name='orderimg',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='제목'),
        ),
        migrations.AddField(
            model_name='orderimg',
            name='order_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.OrderInfo', verbose_name='주문 리스트'),
        ),
        migrations.AddField(
            model_name='orderimg',
            name='plush_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='등록일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderimg',
            name='sectors_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.SectorsCategory', verbose_name='업종'),
        ),
        migrations.AddField(
            model_name='orderimg',
            name='state_at',
            field=models.IntegerField(blank=True, choices=[(0, '대기'), (1, '수정완료'), (2, '확정'), (3, '보류'), (4, '취소'), (5, '무효처리')], default=0, null=True, verbose_name='시안 상태'),
        ),
        migrations.AlterField(
            model_name='orderimg',
            name='state',
            field=models.BooleanField(default=True, verbose_name='노출 상태'),
        ),
    ]
