# Generated by Django 2.1.7 on 2019-10-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0026_auto_20191010_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorderinfo',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='customerorderinfo',
            name='address2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='주소2'),
        ),
        migrations.AlterField(
            model_name='customerorderinfo',
            name='address_detail',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='상세주소'),
        ),
        migrations.AlterField(
            model_name='customerorderinfo',
            name='address_option',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='주소 참고'),
        ),
        migrations.AlterField(
            model_name='customerorderinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='폰 번호'),
        ),
    ]
