# Generated by Django 2.1.7 on 2019-10-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0027_auto_20191010_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderinfo',
            name='address_confirm',
            field=models.BooleanField(default=True),
        ),
    ]
