# Generated by Django 2.1.7 on 2019-10-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0028_customerorderinfo_address_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderinfo',
            name='amount',
            field=models.IntegerField(blank=True, default=1, verbose_name='건수'),
        ),
    ]
