# Generated by Django 2.1.7 on 2019-07-23 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0029_auto_20190723_1633'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='sectorscategory',
            name='is_removed',
        ),
    ]
