# Generated by Django 2.1.7 on 2019-10-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0029_customerorderinfo_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorderinfo',
            name='amount',
        ),
        migrations.AddField(
            model_name='customerorderproduct',
            name='amount',
            field=models.IntegerField(blank=True, default=1, verbose_name='건수'),
        ),
    ]
