# Generated by Django 2.1.7 on 2019-07-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0030_auto_20190723_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='sectorscategory',
            name='slug',
        ),
    ]
