# Generated by Django 2.1.7 on 2019-10-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0030_auto_20191011_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderinfo',
            name='num',
            field=models.IntegerField(default=1, verbose_name='하루 주문 카운트'),
        ),
        migrations.AddField(
            model_name='customerorderinfo',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, '주문 확인중'), (1, '입금대기'), (2, '시안 중'), (3, '제작 중'), (4, '배송 중'), (5, '완료'), (6, '취소'), (6, '보류')], default=0, null=True, verbose_name='주문서 상태'),
        ),
        migrations.AddField(
            model_name='customerorderproduct',
            name='ordering',
            field=models.IntegerField(default=1),
        ),
    ]
