# Generated by Django 2.1.7 on 2019-10-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0031_auto_20191011_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorderinfo',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, '주문 확인중'), (1, '입금대기'), (2, '시안 중'), (3, '제작 중'), (4, '배송 중'), (5, '완료'), (6, '취소'), (7, '보류'), (8, '재인쇄')], default=0, null=True, verbose_name='주문서 상태'),
        ),
    ]
