# Generated by Django 2.1.7 on 2019-10-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0032_auto_20191013_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderinfo',
            name='show_memo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='고객 노출 메모'),
        ),
    ]
