# Generated by Django 2.1.7 on 2019-10-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0034_productpriceapi_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpriceinsideapi',
            name='price_api',
        ),
        migrations.AddField(
            model_name='customerorderinfo',
            name='confirm',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='시안 확인'),
        ),
        migrations.AddField(
            model_name='customerorderinfo',
            name='fix_manager',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='담당자'),
        ),
        migrations.AddField(
            model_name='customerorderinfo',
            name='hoo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='기타 정보'),
        ),
        migrations.AddField(
            model_name='customerorderinfo',
            name='inside_memo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='내부 메모'),
        ),
        migrations.AddField(
            model_name='customerorderinfo',
            name='manager',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='담당자'),
        ),
        migrations.AddField(
            model_name='customerorderinfo',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='발주일'),
        ),
        migrations.AddField(
            model_name='customerorderproduct',
            name='buy_price',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11, verbose_name='buy'),
        ),
        migrations.AddField(
            model_name='customerorderproduct',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='supplier'),
        ),
        migrations.AddField(
            model_name='productpriceapi',
            name='buy',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=11, verbose_name='buy'),
        ),
        migrations.AddField(
            model_name='productpriceapi',
            name='memo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='메모 memo'),
        ),
        migrations.AddField(
            model_name='productpriceapi',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='매입'),
        ),
        migrations.DeleteModel(
            name='ProductPriceInsideAPI',
        ),
    ]
