# Generated by Django 2.1.7 on 2019-10-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0037_auto_20191015_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderproduct',
            name='etc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etc'),
        ),
        migrations.AddField(
            model_name='customerorderproduct',
            name='memo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='memo'),
        ),
    ]
