# Generated by Django 2.1.7 on 2019-10-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0038_auto_20191015_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderinfo',
            name='tax_bool',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customerorderinfo',
            name='fix_manager',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='고정 담당자'),
        ),
        migrations.AlterField(
            model_name='customerorderinfo',
            name='manager',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='작업자'),
        ),
    ]
