# Generated by Django 2.1.7 on 2019-10-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0042_auto_20191016_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderproduct',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='보여질 품목명'),
        ),
    ]
