# Generated by Django 2.1.7 on 2019-10-17 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0044_customerorderinfo_joo_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'verbose_name': '카트 json 텍스트', 'verbose_name_plural': '카트 json 텍스트'},
        ),
    ]
