# Generated by Django 2.1.7 on 2019-10-20 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0045_auto_20191017_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderimg',
            name='order_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_img', to='design.CustomerOrderInfo', verbose_name='주문 리스트'),
        ),
    ]
