# Generated by Django 2.1.7 on 2019-10-24 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0046_auto_20191021_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorderinfo',
            name='joo_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='주문일'),
        ),
    ]
