# Generated by Django 2.1.7 on 2019-10-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0049_mainimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainimg',
            name='kind',
            field=models.CharField(blank=True, max_length=255, verbose_name='품목 종류'),
        ),
        migrations.AddField(
            model_name='mainimg',
            name='state_at',
            field=models.IntegerField(blank=True, choices=[(0, '메인 배너'), (1, '중간 목업')], null=True, verbose_name='이미지 구분'),
        ),
    ]
