# Generated by Django 2.1.7 on 2019-11-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0051_mainimg_origin_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerorderproduct',
            options={'ordering': ['ordering'], 'verbose_name': '고객 주문 품목', 'verbose_name_plural': '고객 주문 품목'},
        ),
        migrations.AddField(
            model_name='customerorderinfo',
            name='deposit_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='차액'),
        ),
        migrations.AddField(
            model_name='customerorderinfo',
            name='deposit_state',
            field=models.BooleanField(default=False, verbose_name='입금 컨펌'),
        ),
        migrations.AlterField(
            model_name='customerorderinfo',
            name='tax_bool',
            field=models.BooleanField(default=True, verbose_name='부가세 정보'),
        ),
        migrations.AlterField(
            model_name='mainimg',
            name='origin_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='샘플 원본 url'),
        ),
    ]
