# Generated by Django 2.1.7 on 2019-11-08 02:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0053_cartproduct_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='id',
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
