# Generated by Django 2.1.7 on 2019-11-14 02:26

import design.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0054_auto_20191108_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('uuid', models.CharField(blank=True, max_length=255, verbose_name='카드 uuid')),
                ('text', models.CharField(blank=True, max_length=255, verbose_name='텍스트 json')),
                ('upload_img', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=design.models.CartDesign.upload_to_upload_img, verbose_name='upload_img')),
                ('upload_file', models.FileField(blank=True, upload_to=design.models.CartDesign.upload_to_upload_file, verbose_name='upload_file')),
                ('order_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_design', to='design.CustomerOrderInfo', verbose_name='주문 리스트')),
            ],
            options={
                'verbose_name': '카트 업로드 데이터',
                'verbose_name_plural': '카트 업로드 데이터',
            },
        ),
    ]
