# Generated by Django 2.1.7 on 2019-11-14 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0055_cartdesign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdesign',
            name='is_removed',
        ),
    ]
