# Generated by Django 2.1.7 on 2019-11-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0056_remove_cartdesign_is_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdesign',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='파일 이름'),
        ),
    ]
