# Generated by Django 2.1.7 on 2019-11-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0058_cartdesign_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdesign',
            name='text',
            field=models.CharField(blank=True, max_length=10000, verbose_name='텍스트 json'),
        ),
        migrations.AlterField(
            model_name='cartpriceproblem',
            name='json_text',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='json data'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='json_text',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='json data'),
        ),
    ]
