# Generated by Django 2.1.7 on 2019-02-27 10:53

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Google',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('site_id', models.IntegerField(verbose_name='site id')),
                ('analytics_uid', models.CharField(blank=True, max_length=128, null=True, verbose_name='Google Analytics UA-ID')),
            ],
            options={
                'verbose_name': 'Google Service',
                'verbose_name_plural': 'Google Services',
            },
        ),
    ]
