# Generated by Django 2.1.7 on 2019-02-25 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_loginlog_owned', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'login log',
                'verbose_name_plural': 'login logs',
            },
        ),
        migrations.CreateModel(
            name='PhoneVerificationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=255, verbose_name='token')),
                ('code', models.CharField(blank=True, max_length=32, verbose_name='code')),
                ('reason', models.CharField(blank=True, max_length=16, verbose_name='reason')),
                ('result_code', models.CharField(blank=True, max_length=16, verbose_name='result code')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='message')),
                ('transaction_id', models.CharField(blank=True, max_length=32, verbose_name='transaction id')),
                ('di', models.CharField(blank=True, max_length=255, verbose_name='di')),
                ('ci', models.TextField(blank=True, verbose_name='ci')),
                ('fullname', models.CharField(blank=True, max_length=32, verbose_name='fullname')),
                ('date_of_birth', models.CharField(blank=True, max_length=16, verbose_name='date of birth')),
                ('gender', models.IntegerField(choices=[(0, 'female'), (1, 'male')], db_index=True, default=1, verbose_name='gender')),
                ('domestic', models.IntegerField(choices=[(0, 'foreign'), (1, 'domestic')], db_index=True, default=1, verbose_name='domestic')),
                ('telecom', models.CharField(blank=True, max_length=16, verbose_name='telecom')),
                ('cellphone', models.CharField(blank=True, max_length=32, verbose_name='cellphone')),
                ('return_message', models.CharField(blank=True, max_length=255, verbose_name='return_message')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_verification_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'phone verification log',
                'verbose_name_plural': 'phone verification logs',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='phone number')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='phone verified')),
                ('phone_verified_status', models.IntegerField(choices=[(0, 'cellphone unverified'), (1, 'cellphone verified'), (2, 'cellphone revoked')], db_index=True, default=0, verbose_name='cellphone verified status')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
