# Generated by Django 2.1.7 on 2019-03-04 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import member.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ask_from', models.CharField(blank=True, max_length=255, verbose_name='name of employees requester')),
                ('ask_part', models.IntegerField(blank=True, choices=[(0, '환불'), (1, '입금'), (2, '영수증/계산서')], db_index=True, verbose_name='division of requests')),
                ('ask_what', models.CharField(blank=True, max_length=255, verbose_name='request comment')),
                ('ask_finish', models.BooleanField(blank=True, default=False, verbose_name='ask_finish')),
            ],
            options={
                'verbose_name': 'ask',
                'verbose_name_plural': 'asks',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('state', models.IntegerField(blank=True, null=True, verbose_name='state')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name of employees')),
                ('join', models.CharField(blank=True, max_length=255, verbose_name='Join')),
                ('leave', models.CharField(blank=True, max_length=255, verbose_name='leave')),
                ('cellphone', models.CharField(blank=True, max_length=255, verbose_name='cellphone')),
                ('join_pic', models.ImageField(blank=True, upload_to=member.models.Employees.upload_to_employees, verbose_name='join picture')),
                ('leave_pic', models.ImageField(blank=True, upload_to=member.models.Employees.upload_to_employees, verbose_name='leave picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'employees',
                'verbose_name_plural': 'employees',
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_loginlog_owned', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'login log',
                'verbose_name_plural': 'login logs',
            },
        ),
        migrations.CreateModel(
            name='PhoneVerificationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=255, verbose_name='token')),
                ('code', models.CharField(blank=True, max_length=32, verbose_name='code')),
                ('reason', models.CharField(blank=True, max_length=16, verbose_name='reason')),
                ('result_code', models.CharField(blank=True, max_length=16, verbose_name='result code')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='message')),
                ('transaction_id', models.CharField(blank=True, max_length=32, verbose_name='transaction id')),
                ('di', models.CharField(blank=True, max_length=255, verbose_name='di')),
                ('ci', models.TextField(blank=True, verbose_name='ci')),
                ('fullname', models.CharField(blank=True, max_length=32, verbose_name='fullname')),
                ('date_of_birth', models.CharField(blank=True, max_length=16, verbose_name='date of birth')),
                ('gender', models.IntegerField(choices=[(0, 'female'), (1, 'male')], db_index=True, default=1, verbose_name='gender')),
                ('domestic', models.IntegerField(choices=[(0, 'foreign'), (1, 'domestic')], db_index=True, default=1, verbose_name='domestic')),
                ('telecom', models.CharField(blank=True, max_length=16, verbose_name='telecom')),
                ('cellphone', models.CharField(blank=True, max_length=32, verbose_name='cellphone')),
                ('return_message', models.CharField(blank=True, max_length=255, verbose_name='return_message')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_verification_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'phone verification log',
                'verbose_name_plural': 'phone verification logs',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('division', models.IntegerField(blank=True, default=1, null=True, verbose_name='division sale=1 purchase=2')),
                ('code', models.IntegerField(blank=True, null=True, unique=True, verbose_name='code number')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='name of company')),
                ('company_keyword', models.CharField(blank=True, max_length=255, verbose_name='key words of company')),
                ('ceo', models.CharField(blank=True, max_length=255, verbose_name='ceo name')),
                ('tax_bill_mail', models.CharField(blank=True, max_length=255, verbose_name='tax bill mail')),
                ('sectors', models.CharField(blank=True, max_length=255, verbose_name='sectors')),
                ('business', models.CharField(blank=True, max_length=255, verbose_name='business')),
                ('tell', models.CharField(blank=True, max_length=255, verbose_name='store tell number')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='keywords of user')),
                ('memo', models.CharField(blank=True, max_length=255, verbose_name='memo of user')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='phone number')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('address2', models.CharField(blank=True, max_length=255, verbose_name='address2')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='phone verified')),
                ('phone_verified_status', models.IntegerField(choices=[(0, 'cellphone unverified'), (1, 'cellphone verified'), (2, 'cellphone revoked')], db_index=True, default=0, verbose_name='cellphone verified status')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('options', models.CharField(blank=True, max_length=255, verbose_name='options for sale')),
                ('confirm', models.CharField(blank=True, max_length=255, verbose_name='confirmed at ')),
                ('discount', models.CharField(blank=True, max_length=255, verbose_name='select discount rate')),
                ('api_state', models.IntegerField(blank=True, null=True, verbose_name='api_state')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Employees', verbose_name='manager')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
        migrations.AddField(
            model_name='ask',
            name='ask_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Employees'),
        ),
    ]
