# Generated by Django 2.1.7 on 2019-04-17 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_loginlog_owned', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'login log',
                'verbose_name_plural': 'login logs',
            },
        ),
        migrations.CreateModel(
            name='PhoneVerificationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=255, verbose_name='token')),
                ('code', models.CharField(blank=True, max_length=32, verbose_name='code')),
                ('reason', models.CharField(blank=True, max_length=16, verbose_name='reason')),
                ('result_code', models.CharField(blank=True, max_length=16, verbose_name='result code')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='message')),
                ('transaction_id', models.CharField(blank=True, max_length=32, verbose_name='transaction id')),
                ('di', models.CharField(blank=True, max_length=255, verbose_name='di')),
                ('ci', models.TextField(blank=True, verbose_name='ci')),
                ('fullname', models.CharField(blank=True, max_length=32, verbose_name='fullname')),
                ('date_of_birth', models.CharField(blank=True, max_length=16, verbose_name='date of birth')),
                ('gender', models.IntegerField(choices=[(0, 'female'), (1, 'male')], db_index=True, default=1, verbose_name='gender')),
                ('domestic', models.IntegerField(choices=[(0, 'foreign'), (1, 'domestic')], db_index=True, default=1, verbose_name='domestic')),
                ('telecom', models.CharField(blank=True, max_length=16, verbose_name='telecom')),
                ('cellphone', models.CharField(blank=True, max_length=32, verbose_name='cellphone')),
                ('return_message', models.CharField(blank=True, max_length=255, verbose_name='return_message')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_verification_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'phone verification log',
                'verbose_name_plural': 'phone verification logs',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('division', models.IntegerField(blank=True, default=1, null=True, verbose_name='구분 판매처=1 매입처=2')),
                ('code', models.IntegerField(blank=True, null=True, unique=True, verbose_name='사업자번호')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='업체명')),
                ('company_keyword', models.CharField(blank=True, max_length=255, verbose_name='검색창 내용/ 키워드')),
                ('ceo', models.CharField(blank=True, max_length=255, verbose_name='대표자명')),
                ('tax_bill_mail', models.CharField(blank=True, max_length=255, verbose_name='이메일')),
                ('sectors', models.CharField(blank=True, max_length=255, verbose_name='업종')),
                ('business', models.CharField(blank=True, max_length=255, verbose_name='업태')),
                ('tell', models.CharField(blank=True, max_length=255, verbose_name='매장번호')),
                ('keywords', models.CharField(blank=True, max_length=1000, verbose_name='키워드')),
                ('memo', models.CharField(blank=True, max_length=255, verbose_name='메모')),
                ('phone', models.CharField(blank=True, max_length=17, null=True, verbose_name='phone number')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='주소')),
                ('address2', models.CharField(blank=True, max_length=255, verbose_name='주소2')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='phone verified')),
                ('phone_verified_status', models.IntegerField(choices=[(0, '본인인증 X'), (1, '본인인증 O'), (2, '본인인증 취소')], db_index=True, default=0, verbose_name='cellphone verified status')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('options', models.CharField(blank=True, max_length=255, verbose_name='결재/포함/택배')),
                ('confirm', models.CharField(blank=True, max_length=255, verbose_name='시안 확인')),
                ('discount', models.CharField(blank=True, max_length=255, verbose_name='할인율')),
                ('api_state', models.IntegerField(blank=True, default=0, null=True, verbose_name='api_state')),
                ('manager', models.CharField(blank=True, max_length=100, null=True, verbose_name='담당자')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='사업자 상태')),
                ('state_select', models.IntegerField(blank=True, choices=[(0, '정상'), (1, '폐업')], default=0, null=True, verbose_name='사업자 상태')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
