# Generated by Django 2.1.7 on 2019-02-26 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import member.models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('state', models.IntegerField(blank=True, max_length=3, null=True, verbose_name='state')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name of employees')),
                ('join', models.CharField(blank=True, max_length=255, verbose_name='Join')),
                ('leave', models.CharField(blank=True, max_length=255, verbose_name='leave')),
                ('cellphone', models.CharField(blank=True, max_length=255, verbose_name='cellphone')),
                ('join_pic', models.ImageField(blank=True, upload_to=member.models.Employees.upload_to_employees, verbose_name='join picture')),
                ('leave_pic', models.ImageField(blank=True, upload_to=member.models.Employees.upload_to_employees, verbose_name='leave picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'employees',
                'verbose_name_plural': 'employees',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='address2',
            field=models.CharField(blank=True, max_length=255, verbose_name='address2'),
        ),
        migrations.AddField(
            model_name='profile',
            name='api_state',
            field=models.IntegerField(blank=True, max_length=3, null=True, verbose_name='api_state'),
        ),
        migrations.AddField(
            model_name='profile',
            name='business',
            field=models.CharField(blank=True, max_length=255, verbose_name='business'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ceo',
            field=models.CharField(blank=True, max_length=255, verbose_name='ceo name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='code',
            field=models.IntegerField(blank=True, max_length=11, null=True, unique=True, verbose_name='code number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='confirm',
            field=models.CharField(blank=True, max_length=255, verbose_name='confirmed at '),
        ),
        migrations.AddField(
            model_name='profile',
            name='discount',
            field=models.CharField(blank=True, max_length=255, verbose_name='select discount rate'),
        ),
        migrations.AddField(
            model_name='profile',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='keywords of user'),
        ),
        migrations.AddField(
            model_name='profile',
            name='memo',
            field=models.CharField(blank=True, max_length=255, verbose_name='memo of user'),
        ),
        migrations.AddField(
            model_name='profile',
            name='options',
            field=models.CharField(blank=True, max_length=255, verbose_name='options for sale'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sectors',
            field=models.CharField(blank=True, max_length=255, verbose_name='sectors'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tax_bill_mail',
            field=models.CharField(blank=True, max_length=255, verbose_name='tax bill mail'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tell',
            field=models.CharField(blank=True, max_length=255, verbose_name='store tell number'),
        ),
    ]
