# Generated by Django 2.1.7 on 2019-04-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state_select',
            field=models.IntegerField(blank=True, choices=[(0, '정상'), (1, '폐업')], default=0, null=True, verbose_name='사업자 상태'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='api_state',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='api_state'),
        ),
    ]
