# Generated by Django 2.1.7 on 2019-03-04 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 3, 0, 56, 15, 640787), verbose_name='finish_date'),
        ),
    ]
