# Generated by Django 2.1.7 on 2019-03-27 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 25, 18, 25, 51, 738767), verbose_name='등록일+90일'),
        ),
    ]
