# Generated by Django 2.1.7 on 2019-05-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.IntegerField(null=True, unique=True, verbose_name='사업자번호'),
        ),
    ]
