# Generated by Django 2.1.7 on 2019-03-27 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20190327_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 25, 18, 27, 30, 730010), verbose_name='등록일+90일'),
        ),
    ]
