# Generated by Django 2.1.7 on 2019-08-09 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0008_orderimg_employees'),
        ('member', '0003_auto_20190531_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sectors_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.SectorsCategory', verbose_name='업종'),
        ),
    ]
