# Generated by Django 2.1.7 on 2019-09-20 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('design', '0010_cartproduct'),
        ('member', '0004_profile_sectors_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('managing_pk', models.IntegerField(blank=True, null=True, verbose_name='managing id')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='사업자번호')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='업체명')),
                ('ceo', models.CharField(blank=True, max_length=255, verbose_name='대표자명')),
                ('tax_bill_mail', models.CharField(blank=True, max_length=255, verbose_name='이메일')),
                ('sectors', models.CharField(blank=True, max_length=255, verbose_name='업종')),
                ('business', models.CharField(blank=True, max_length=255, verbose_name='업태')),
                ('tell', models.CharField(blank=True, max_length=255, verbose_name='매장번호')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='phone number')),
                ('memo', models.CharField(blank=True, max_length=255, verbose_name='메모')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='주소')),
                ('address2', models.CharField(blank=True, max_length=255, verbose_name='주소2')),
                ('address_detail', models.CharField(blank=True, max_length=255, verbose_name='상세주소')),
                ('address_option', models.CharField(blank=True, max_length=255, verbose_name='주소 참고')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='사업자 상태')),
                ('state_select', models.IntegerField(blank=True, choices=[(0, '정상'), (1, '폐업')], default=0, null=True, verbose_name='사업자 상태')),
                ('bill_select', models.IntegerField(blank=True, choices=[(0, '세금계산서'), (1, '사업자 지출증빙'), (2, '현금 영수증'), (3, '미발행')], default=0, null=True, verbose_name='사업자 상태')),
                ('sectors_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.SectorsCategory', verbose_name='업종')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '고객이 입력한 프로필',
                'verbose_name_plural': '고객이 입력한 프로필',
            },
        ),
    ]
