# Generated by Django 2.1.7 on 2019-09-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_customerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='bill_select',
            field=models.IntegerField(blank=True, choices=[(0, '세금계산서'), (1, '사업자 지출증빙'), (2, '현금 영수증'), (3, '미발행')], null=True, verbose_name='사업자 상태'),
        ),
    ]
