# Generated by Django 2.1.7 on 2019-10-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20191010_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='담당 직원'),
        ),
    ]
