# Generated by Django 2.1.7 on 2019-08-02 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
import managing.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0003_auto_20190531_1537'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('ask_from', models.CharField(blank=True, max_length=255, verbose_name='질문자')),
                ('ask_part', models.IntegerField(choices=[(0, '환불'), (1, '입금 요청'), (2, '영수증/계산서'), (3, '기타')], db_index=True, verbose_name='division of requests')),
                ('ask_what', models.CharField(blank=True, max_length=255, verbose_name='요청내용')),
                ('ask_finish', models.BooleanField(blank=True, default=False, verbose_name='ask_finish')),
                ('ask_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='받는사람')),
            ],
            options={
                'verbose_name': '요청사항',
                'verbose_name_plural': '요청사항',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='날짜')),
                ('bank', models.CharField(blank=True, max_length=100, null=True, verbose_name='은행명')),
                ('part', models.CharField(blank=True, max_length=100, null=True, verbose_name='입/출금')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='입금자명')),
                ('amount', models.IntegerField(blank=True, verbose_name='입금액')),
                ('memo', models.CharField(blank=True, max_length=255, verbose_name='메모')),
                ('bill', models.CharField(blank=True, max_length=255, verbose_name='영수처리')),
                ('state', models.BooleanField(blank=True, default=False, verbose_name='sate of deposit')),
            ],
            options={
                'verbose_name': '입금내역',
                'verbose_name_plural': '입금내역',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('discount1', models.IntegerField(blank=True, verbose_name='discount1')),
                ('discount2', models.IntegerField(blank=True, verbose_name='discount2')),
                ('discount3', models.IntegerField(blank=True, verbose_name='discount3')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.ProductText')),
            ],
            options={
                'verbose_name': '할인율',
                'verbose_name_plural': '할인율',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('group', models.IntegerField(choices=[(0, '관리자'), (1, '팀장'), (2, '디자이너'), (3, '알바'), (4, '기타')], db_index=True, default=2, verbose_name='그룹선택')),
                ('state', models.BooleanField(default=True, verbose_name='state')),
                ('name', models.CharField(max_length=255, verbose_name='name of employees')),
                ('join', models.DateField(blank=True, null=True, verbose_name='Join')),
                ('leave', models.DateField(blank=True, null=True, verbose_name='leave')),
                ('cellphone', models.CharField(blank=True, max_length=255, null=True, verbose_name='cellphone')),
                ('join_pic', models.ImageField(blank=True, null=True, upload_to=managing.models.Employees.upload_to_employees, verbose_name='join picture')),
                ('leave_pic', models.ImageField(blank=True, null=True, upload_to=managing.models.Employees.upload_to_employees, verbose_name='leave picture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '직원',
                'verbose_name_plural': '직원',
            },
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('employees', models.CharField(blank=True, max_length=255, null=True, verbose_name='담당자')),
                ('content', models.CharField(blank=True, max_length=255, null=True, verbose_name='내용')),
                ('confirm', models.BooleanField(default=False, verbose_name='확인')),
                ('common', models.BooleanField(default=False, verbose_name='개인/공유')),
                ('importance', models.BooleanField(default=False, verbose_name='중요도')),
                ('notice', models.BooleanField(default=False, verbose_name='공지사항')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.OrderInfo', verbose_name='품목 연결')),
            ],
            options={
                'verbose_name': '할일 to_do',
                'verbose_name_plural': '할일 to_do',
            },
        ),
        migrations.CreateModel(
            name='OrderWithDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('division', models.IntegerField(blank=True, null=True, verbose_name='수동 확인')),
                ('deposit_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_with', to='managing.Deposit')),
                ('order_info_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_info_with', to='design.OrderInfo')),
            ],
            options={
                'verbose_name': '입금 연결',
                'verbose_name_plural': '입금 연결',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('state', models.IntegerField(blank=True, null=True, verbose_name='state')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name of product')),
                ('standard', models.CharField(blank=True, max_length=255, verbose_name='standard')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=4, max_digits=11, verbose_name='purchase_price')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=4, max_digits=11, verbose_name='sale_price')),
                ('delivery_charge', models.IntegerField(blank=True, verbose_name='delivery charge')),
                ('quantity', models.IntegerField(blank=True, verbose_name='min quantity')),
                ('group', models.CharField(blank=True, max_length=255, verbose_name='group of product')),
                ('manage_code', models.CharField(blank=True, max_length=255, verbose_name='manage_code')),
                ('product_img', models.ImageField(blank=True, upload_to=managing.models.Product.upload_to_product, verbose_name='product_img')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Profile')),
            ],
            options={
                'verbose_name': '품목',
                'verbose_name_plural': '품목',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('plush_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='샘플명')),
                ('keyword', models.CharField(blank=True, max_length=255, verbose_name='키워드')),
                ('group', models.CharField(blank=True, max_length=255, verbose_name='샘플 패키지')),
                ('state', models.BooleanField(default=True, verbose_name='샘플 상태')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='링크 url')),
                ('images', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=managing.models.Sample.upload_to_sample, verbose_name='sample_img')),
                ('images_thumbnail', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='sample/thumbnail/', verbose_name='thumbnail')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.Category', verbose_name='카테고리')),
                ('employees', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='직원명')),
                ('sectors_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.SectorsCategory', verbose_name='업종')),
            ],
            options={
                'verbose_name': '샘플',
                'verbose_name_plural': '샘플',
            },
        ),
        migrations.CreateModel(
            name='SpecialPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('new_price', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='new_price')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.ProductText')),
            ],
            options={
                'verbose_name': '특별가격',
                'verbose_name_plural': '특별가격',
            },
        ),
    ]
