# Generated by Django 2.1.7 on 2019-03-27 09:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import managing.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0002_auto_20190327_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name of the deposit')),
                ('amount', models.IntegerField(blank=True, verbose_name='amount')),
                ('memo', models.CharField(blank=True, max_length=255, verbose_name='memo and company name of deposit')),
                ('bill', models.CharField(blank=True, max_length=255, verbose_name='bill sate of deposit')),
                ('state', models.BooleanField(blank=True, default=False, verbose_name='sate of deposit')),
            ],
            options={
                'verbose_name': '입금내역',
                'verbose_name_plural': '입금내역',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('discount1', models.IntegerField(blank=True, verbose_name='discount1')),
                ('discount2', models.IntegerField(blank=True, verbose_name='discount2')),
                ('discount3', models.IntegerField(blank=True, verbose_name='discount3')),
            ],
            options={
                'verbose_name': '할인율',
                'verbose_name_plural': '할인율',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('state', models.IntegerField(blank=True, null=True, verbose_name='state')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name of product')),
                ('standard', models.CharField(blank=True, max_length=255, verbose_name='standard')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, verbose_name='purchase_price')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, verbose_name='sale_price')),
                ('delivery_charge', models.IntegerField(blank=True, verbose_name='delivery charge')),
                ('quantity', models.IntegerField(blank=True, verbose_name='min quantity')),
                ('group', models.CharField(blank=True, max_length=255, verbose_name='group of product')),
                ('manage_code', models.CharField(blank=True, max_length=255, verbose_name='manage_code')),
                ('product_img', models.ImageField(blank=True, upload_to=managing.models.Product.upload_to_product, verbose_name='product_img')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Profile')),
            ],
            options={
                'verbose_name': '품목',
                'verbose_name_plural': '품목',
            },
        ),
        migrations.AddField(
            model_name='discount',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managing.Product'),
        ),
    ]
