# Generated by Django 2.1.7 on 2019-03-04 04:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import managing.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('state', models.IntegerField(blank=True, null=True, verbose_name='state')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name of product')),
                ('standard', models.CharField(blank=True, max_length=255, verbose_name='standard')),
                ('purchase_price', models.FloatField(blank=True, verbose_name='purchase_price')),
                ('sale_price', models.FloatField(blank=True, verbose_name='sale_price')),
                ('delivery_charge', models.IntegerField(blank=True, verbose_name='delivery charge')),
                ('quantity', models.IntegerField(blank=True, verbose_name='min quantity')),
                ('group', models.CharField(blank=True, max_length=255, verbose_name='group of product')),
                ('manage_code', models.CharField(blank=True, max_length=255, verbose_name='manage_code')),
                ('product_img', models.ImageField(blank=True, upload_to=managing.models.Product.upload_to_product, verbose_name='product_img')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Profile')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('plush_date', models.DateTimeField(auto_now_add=True, verbose_name='plush_date')),
                ('finish_date', models.DateTimeField(default=datetime.datetime(2019, 6, 2, 13, 9, 5, 215615), verbose_name='finish_date')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name of sample')),
                ('keyword', models.CharField(blank=True, max_length=255, verbose_name='keyword')),
                ('group', models.CharField(blank=True, max_length=255, verbose_name='group of sample')),
                ('sample_img', models.ImageField(blank=True, upload_to=managing.models.Sample.upload_to_sample, verbose_name='sample_img')),
                ('employees', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Employees')),
            ],
            options={
                'verbose_name': 'sample',
                'verbose_name_plural': 'samples',
            },
        ),
    ]
