# Generated by Django 2.1.7 on 2019-04-23 07:38

from django.db import migrations, models
import managing.models


class Migration(migrations.Migration):

    dependencies = [
        ('managing', '0002_auto_20190423_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='cellphone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='cellphone'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='join',
            field=models.DateField(blank=True, null=True, verbose_name='Join'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='join_pic',
            field=models.ImageField(blank=True, null=True, upload_to=managing.models.Employees.upload_to_employees, verbose_name='join picture'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='leave',
            field=models.DateField(blank=True, null=True, verbose_name='leave'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='leave_pic',
            field=models.ImageField(blank=True, null=True, upload_to=managing.models.Employees.upload_to_employees, verbose_name='leave picture'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name of employees'),
        ),
    ]
