# Generated by Django 2.1.7 on 2019-10-04 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managing', '0003_customermemo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermemo',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_memo', to=settings.AUTH_USER_MODEL),
        ),
    ]
