# Generated by Django 2.1.7 on 2019-04-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing', '0003_auto_20190423_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='state',
            field=models.BooleanField(default=True, verbose_name='샘플 상태'),
        ),
    ]
