# Generated by Django 2.1.7 on 2019-05-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_auto_20190423_0045'),
        ('managing', '0014_auto_20190513_1729'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDo',
            new_name='Memo',
        ),
    ]
