# Generated by Django 2.1.7 on 2019-05-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing', '0015_auto_20190514_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='group',
            field=models.IntegerField(choices=[(0, '관리자'), (1, '팀장'), (2, '디자이너'), (3, '알바'), (4, '기타')], db_index=True, default=2, verbose_name='그룹선택'),
        ),
    ]
