# Generated by Django 2.1.7 on 2019-07-08 07:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('managing', '0017_auto_20190622_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderWithDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('balance', models.IntegerField(blank=True, null=True, verbose_name='잔액')),
                ('deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit', to='managing.Deposit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
