# Generated by Django 2.1.7 on 2019-07-08 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managing', '0018_orderwithdeposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderwithdeposit',
            name='deposit',
        ),
        migrations.AddField(
            model_name='orderwithdeposit',
            name='deposit_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_with', to='managing.Deposit'),
        ),
    ]
