# Generated by Django 2.1.7 on 2019-07-08 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0025_remove_orderlist_is_removed'),
        ('managing', '0019_auto_20190708_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderwithdeposit',
            name='order_info_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_info_with', to='design.OrderInfo'),
        ),
    ]
