# Generated by Django 2.1.7 on 2019-07-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing', '0021_auto_20190710_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderwithdeposit',
            name='balance',
        ),
        migrations.AddField(
            model_name='orderwithdeposit',
            name='division',
            field=models.IntegerField(blank=True, null=True, verbose_name='수동 확인'),
        ),
    ]
