# Generated by Django 2.1.7 on 2019-07-16 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managing', '0022_auto_20190711_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='sample_img',
            new_name='images',
        ),
    ]
